# Generated by Django 4.0.5 on 2022-06-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_store_delete_chocolatefeast_product_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(to='api.store'),
        ),
    ]
