# Generated by Django 4.0.5 on 2022-06-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_promotions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promotions',
            new_name='Promotion',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='numberOfWraps',
            new_name='number_of_wraps',
        ),
    ]
