# Generated by Django 4.0.5 on 2022-06-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_promotion_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
