# Generated by Django 4.0.5 on 2022-06-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_delete_promotion"),
    ]

    operations = []
