# Generated by Django 4.0.5 on 2022-06-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_product_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='promotion',
            new_name='promotions',
        ),
    ]
